### PR TITLE
add timestamp to output

### PR DESCRIPTION
**Pull request by jmariomejiap**
## Changes

This PR adds a timestamp to the output, 

image

### CODE REVIEW

**Comment by przmv** [comment]
Let's use some more wide-spread datetime format https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON

**Comment by przmv** [comment]
Probably it makes sense to add timestamp to `custom_fields`, so it would become visible on the platform, WDYT?

**Comment by prees1** [comment]
Good stuff

**Comment by przmv** [comment]
LGTM @jmariomejiap 
Is there any documentation on `/proc/driver/rtc`?

**Comment by jmariomejiap** [comment]
> LGTM @jmariomejiap Is there any documentation on `/proc/driver/rtc`?

Is something like [this](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-proc-dir-driver) what you are looking for?

**Pull request merged**
